ALTER TABLE "Bag"
DROP
CONSTRAINT IF EXISTS "PK_Bag" CASCADE;

ALTER TABLE "BagGameItem"
DROP
CONSTRAINT IF EXISTS "PK_BagGameItem" CASCADE,
    DROP
CONSTRAINT IF EXISTS "FK_BagGameItem_Bag_Id" CASCADE,
    DROP
CONSTRAINT IF EXISTS "FK_BagGameItem_GameItem_GameItemId" CASCADE;

TRUNCATE "Bag";
TRUNCATE "BagGameItem";